### ISSUE TITLE
Unmute audio by default

### ISSUE THREAD

**Issue by timelessthee** [jkeen/latlmes#6]
Videos are muted on first visit.
Is this intentional?
It seems the first time a user visits the site, they have to unmute the audio. 
If they unmute, on all subsequent visits the video then has audio on page open.

But this doesn't work for the purpose of tricking people with the link?

**Comment by jkeen** [comment]
Unfortunately there are certain restrictions with browsers that I can't get around. Modern browsers won't autoplay a video that isn't muted unless the user has specifically opted into to allowing that site to do so. It's a great move in the battle against annoying advertisements, and a real blow to prank videos.

**Comment by jkeen** [comment]
The only way around it is to get the user to click on the page first, thereby triggering the video. A while back when these new browser restrictions first came out I tested out some versions of the site that required a click on a fake popup thing which would then play the video. 

It was unanimously hated by the people I tried it on.
